import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../styles/globals.scss";

const inter = localFont({
  src: '../public/fonts/inter/InterVariable.woff2',
  variable: '--font-inter',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: "game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={inter.variable}
    >
      <body className="body">{children}</body>
    </html>
  );
}
